# MongoDB Configuration Profile
spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://mertunsal0_db_user:geWPGbaakEdWNgjT@munsal-cluster.redvguc.mongodb.net/?retryWrites=true&w=majority&appName=munsalCluster}
      database: ${MONGODB_DATABASE:ikea}

management:
  health:
    mongo:
      enabled: true


