# MongoDB Configuration Profile
spring:
  data:
    mongodb:
      # Prefer URI; overrides host/port if provided
      uri: ${MONGODB_URI:mongodb+srv://bnymnyrls_db_user:GMvGHyabysKCW7PC@cluster0.ngrkjxc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      database: ${MONGODB_DATABASE:ikea}

management:
  health:
    mongo:
      enabled: true


