spring:
  application:
    name: warehouse-command-api
  profiles:
    active: logging,management,mongo

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha

# Server Configuration
server:
  port: ${PORT:8083}
  servlet:
    context-path: /

# Application Information
info:
  app:
    name: ${spring.application.name}
    description: Warehouse Data Consumer Service for IKEA
    version: '0.0.1-SNAPSHOT'
    encoding: 'UTF-8'
    java:
      version: '21'

#  exporters set as none, as this is a demo project and we don't want to send any data to any external service
otel:
  resource:
    attributes:
      deployment.environment: ${ACTIVE_PROFILE:dev}
      service:
        name: ${OTEL_SERVICE_NAME:warehouse-data-ingestion-service}
        namespace: ${OTEL_SERVICE_NAMESPACE:ikea-dev}
  exporter:
    otlp:
      endpoint: ""
      compression: ${OTEL_EXPORTER_OTLP_METRICS_COMPRESSION:gzip}
      protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:http/protobuf}
  instrumentation:
    kafka:
      enabled: true
      autoconfigure-interceptor: true
      experimental-span-attributes: true
  traces:
    exporter: none #console
    sampler.arg: ${OTEL_TRACES_SAMPLER_ARG:0.1}
    sampler: always_on
  logs:
    exporter: none #console
  metrics:
    exporter: none #console